spring:
  datasource:
    url:  jdbc:h2:file:~/data/raflog2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8081
node:
  id: 2
  peers:
    1:
      id  : 1
      host: "localhost"
      port: 8080
    3:
      id: 3
      host: "localhost"
      port: 8082